# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/bbox_func/03_nms.ipynb.

# %% auto 0
__all__ = ['monai_nms']

# %% ../../nbs/bbox_func/03_nms.ipynb 1
from monai.data.box_utils import non_max_suppression
#TODO: Implement own and use DIoU

# %% ../../nbs/bbox_func/03_nms.ipynb 2
def monai_nms(inputs, nms_thr, cnf_thr, cpu=True):
    boxes, scores, labels = (
        inputs["boxes"],
        inputs["labels_scores"],
        inputs["labels"],
    )
    # final NMS
    keep = non_max_suppression(boxes, scores, nms_thresh=nms_thr)
    boxes, scores, labels = boxes[keep], scores[keep], labels[keep]
    # final CNF_thr
    keep = scores > cnf_thr
    boxes, scores, labels = boxes[keep], scores[keep], labels[keep]

    # save as dict
    final = {}
    if cpu : 
        final["boxes"] = boxes.cpu().numpy()
        final["scores"] = scores.cpu().numpy()
        final["labels"] = labels.cpu().numpy()
    else :
        final["boxes"] = boxes
        final["scores"] = scores
        final["labels"] = labels
    return final
