# Val transforms if test transforms is not mentioned
# use the val transforms as test transforms
val_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image","mask"]
    - _target_: src.common.transforms.monai_extras.FixedZDim
      keys: ["image", "mask"]
      target_z: 32
      pad_value: 0
      random_center_crop: False
    - _target_ : src.common.transforms.monai_extras.CropHeadCT
      image_key: "image"
      mask_keys: ["mask"]
    - _target_ : src.common.transforms.monai_extras.BinarizeSegMask
      keys: ["mask"]
    - _target_: src.common.transforms.monai_extras.ResizeImage
      keys: ["image","mask"]
      size: [224,224]
      interpolation: 
        image: bicubic
        mask: nearest
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["brain_window","blood_window","bone_window"]
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image","mask"]
      
# train transforms
train_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["mask"]
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image" , "icv_mask","hemi_seperator_mask"]
      to_tensor: False
    - _target_: src.common.transforms.monai_extras.GenerateICV
      image_key: "image"
    - _target_: src.common.transforms.monai_extras.ExtractFalx
      key : hemi_seperator_mask
      icv_mask_key: icv_mask
      dilation_kernel_size: 15
      slc_range: [16,28]
      output_key: falx
    - _target_: src.common.transforms.monai_extras.ExtractICVBoundary
      keys: ["icv_mask"]
      di: 3
      er: 9
      slc_range: [14,28]
    - _target_: src.common.transforms.monai_extras.ToTensor
      keys: ["image","icv_mask","falx"]
    - _target_: src.common.transforms.monai_extras.FixedZDim
      keys: ["image", "mask","icv_mask","falx"]
      target_z: 32
      pad_value: 0
      random_center_crop: True
    - _target_: src.common.transforms.monai_extras.RandomNoise
      keys: ["image"]
      intensity: 10
      mode: "hct_thin"
      prob: 0.5
    - _target_: src.common.transforms.monai_extras.RandomSmoothSharpen
      keys: ["image"]
      intensity: 0.6
      kernel_size: 5
      prob: 0.5
    - _target_ : src.common.transforms.monai_extras.ApplyCrop
      keys: ["image","mask","icv_mask","falx"]
      crop_key: crop
    - _target_ : src.common.transforms.monai_extras.BinarizeSegMask
      keys: ["mask","icv_mask","falx"]
    - _target_: src.common.transforms.monai_extras.ResizeImage
      size: [224,224]
      keys: ["image", "mask","icv_mask","falx"]
      interpolation: 
        image: bicubic
        mask: nearest
        icv_mask: nearest
        falx: nearest
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["brain_window","blood_window","bone_window"]
    - _target_: src.common.transforms.monai_extras.RandomHorizontalFlip 
      prob: 0.5
      keys: ["image","mask","icv_mask","falx"]
    - _target_: src.common.transforms.monai_extras.RandomAffine
      prob: 0.6
      keys: ["image","mask","icv_mask","falx"]
      scale: [0.8, 1.2]
      degrees: [-15,15]
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image","mask","icv_mask","falx"]
    