# Val transforms if test transforms is not mentioned
# use the val transforms as test transforms
val_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image" , "lobe_label"]
    - _target_: src.common.transforms.monai_extras.CTCrop
      image_key: image
      mask_keys: ["lobe_label"]
    - _target_: src.common.transforms.monai_extras.Resize3D
      image_key : image
      label_keys: ["lobe_label"]
      spatial_size: [160,224,224]
    # - _target_: src.common.transforms.monai_extras.ResizeImage
    #   keys: ["image","lung_label", "lobe_label"]
    #   size: [224, 224]
    #   interpolation: 
    #     image: bicubic
    #     lung_label: nearest
    #     lobe_label: nearest
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["Lung"]
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image" , "lung_label" , "lobe_label"]

# train transforms
train_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image" , "lobe_label"]
    - _target_: src.common.transforms.monai_extras.CTCrop
      image_key: image
      mask_keys: ["lobe_label"]
    # - _target_: src.common.transforms.monai_extras.ResizeImage
    #   size: [224, 224]
    #   keys: ["image","lung_label", "lobe_label"]
    #   interpolation: 
    #     image: bicubic
    #     lung_label: nearest
    #     lobe_label: nearest
    - _target_: src.common.transforms.monai_extras.Resize3D
      image_key : image
      label_keys: ["lobe_label"]
      spatial_size: [160,224,224]
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["Lung"]
    - _target_: src.common.transforms.monai_extras.RandomAffine
      prob: 0.7
      keys: ["image", "lobe_label"]
      scale: [0.9, 1.3]
      degrees: [-15,15]
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image" , "lobe_label"]
