# Val transforms if test transforms is not mentioned
# use the val transforms as test transforms
val_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image" , "lung_label" , "lobe_label"]
    # - _target_: src.common.transforms.monai_extras.CTCrop
    #   image_key: image
    #   mask_keys: ["lung_label", "lobe_label"]
    #   random_prob : 0
    - _target_: src.common.transforms.monai_extras.Resize3D
      image_key : image
      label_keys: ["lung_label" , "lobe_label"]
      spatial_size: [160,224,224]  #resnet unet
    
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["Custom LungD" , "Lung" , "Custom LungA"]
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image" , "lung_label" , "lobe_label"]

# train transforms
train_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image" , "lung_label" , "lobe_label"]
    # - _target_: src.common.transforms.monai_extras.CTCrop
    #   image_key: image
    #   mask_keys: ["lung_label", "lobe_label"]
    #   random_prob : 0.5
    - _target_ : src.common.transforms.monai_extras.RandomZPad
      keys: ["image" , "lung_label" , "lobe_label"]
      target_z: 160
      pad_value : min
      prob: 0.5
    - _target_ : src.common.transforms.monai_extras.ResampleSlice
      keys: ["image" , "lung_label" , "lobe_label"]
      spatial_z_threshold: 160
      random_prob: 0.5
    - _target_: src.common.transforms.monai_extras.Resize3D
      image_key : image
      label_keys: ["lung_label" , "lobe_label"]
      spatial_size: [160,224,224]
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["Custom LungD" , "Lung" , "Custom LungA"]
    - _target_: src.common.transforms.monai_extras.RandomAffine
      prob: 0.8
      keys: ["image", "lung_label", "lobe_label"]
      scale: [0.8, 1.2]
      degrees: [-15,15]
    - _target_ : src.common.transforms.monai_extras.RandomGaussianBlur
      keys: ["image"]
      kernel_size: 3
      sigma: [0.1, 2.0]
      prob: 0.1
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image" , "lung_label" , "lobe_label"]


