# Val transforms if test transforms is not mentioned
# use the val transforms as test transforms
test_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadSitkData
      keys: ["image"]
    # - _target_: src.common.transforms.monai_extras.LoadDcmData
    #   keys: ["mask"]
    # - _target_: src.common.transforms.monai_extras.ToTensor
    #   keys: ["slice_label"]
    # - _target_: src.common.transforms.monai_extras.IgnoreIndexMask
    #   ignore_index: -100
    #   key_shape:
    #     mask : [32,512,512]
    # - _target_: src.common.transforms.monai_extras.FixedZDim
    #   keys: ["image", "slice_label", "mask"]
    #   target_z: 32
    #   pad_value: 0
    #   random_center_crop: False
    # - _target_ : src.common.transforms.monai_extras.ApplyCrop
    #   keys: ["image","mask"]
    #   crop_key: crop
    # - _target_ : src.common.transforms.monai_extras.BinarizeSegMask
    #   keys: ["mask"]
    - _target_ : src.common.transforms.monai_extras.CropHeadCT
      image_key: image
    - _target_: src.common.transforms.monai_extras.ResizeImage
      keys: ["image"]
      size: [224,224]
      interpolation: 
        image: bicubic
        mask: nearest
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["brain_window","blood_window","bone_window"]
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image"]
      
# train transforms
train_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image"]
    - _target_: src.common.transforms.monai_extras.LoadDcmData
      keys: ["mask"]
    - _target_: src.common.transforms.monai_extras.ToTensor
      keys: ["slice_label"]
    - _target_: src.common.transforms.monai_extras.IgnoreIndexMask
      ignore_index: -100
      key_shape:
        mask : [32,512,512]
    - _target_: src.common.transforms.monai_extras.FixedZDim
      keys: ["image", "slice_label", "mask"]
      target_z: 32
      pad_value: 0
      random_center_crop: True
    - _target_: src.common.transforms.monai_extras.RandomNoise
      keys: ["image"]
      intensity: 10
      mode: "hct_thin"
      prob: 0.5
    - _target_: src.common.transforms.monai_extras.RandomSmoothSharpen
      keys: ["image"]
      intensity: 0.6
      kernel_size: 5
      prob: 0.5
    - _target_ : src.common.transforms.monai_extras.ApplyCrop
      keys: ["image","mask"]
      crop_key: crop
    - _target_ : src.common.transforms.monai_extras.BinarizeSegMask
      keys: ["mask"]
    - _target_: src.common.transforms.monai_extras.ResizeImage
      size: [224,224]
      keys: ["image", "mask"]
      interpolation: 
        image: bicubic
        mask: nearest
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["brain_window","blood_window","bone_window"]
    - _target_: src.common.transforms.monai_extras.RandomHorizontalFlip 
      prob: 0.5
      keys: ["image","mask"]
    - _target_: src.common.transforms.monai_extras.RandomAffine
      prob: 0.6
      keys: ["image","mask"]
      scale: [0.8, 1.2]
      degrees: [-15,15]
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image","mask"]
    
# val transforms
val_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image"]
    - _target_: src.common.transforms.monai_extras.LoadDcmData
      keys: ["mask"]
    - _target_: src.common.transforms.monai_extras.ToTensor
      keys: ["slice_label"]
    - _target_: src.common.transforms.monai_extras.IgnoreIndexMask
      ignore_index: -100
      key_shape:
        mask : [32,512,512]
    - _target_: src.common.transforms.monai_extras.FixedZDim
      keys: ["image", "slice_label", "mask"]
      target_z: 32
      pad_value: 0
      random_center_crop: True
    - _target_: src.common.transforms.monai_extras.RandomNoise
      keys: ["image"]
      intensity: 10
      mode: "hct_thin"
      prob: 0.5
    - _target_: src.common.transforms.monai_extras.RandomSmoothSharpen
      keys: ["image"]
      intensity: 0.6
      kernel_size: 5
      prob: 0.5
    - _target_ : src.common.transforms.monai_extras.ApplyCrop
      keys: ["image","mask"]
      crop_key: crop
    - _target_ : src.common.transforms.monai_extras.BinarizeSegMask
      keys: ["mask"]
    - _target_: src.common.transforms.monai_extras.ResizeImage
      size: [224,224]
      keys: ["image", "mask"]
      interpolation: 
        image: bicubic
        mask: nearest
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["brain_window","blood_window","bone_window"]
    - _target_: src.common.transforms.monai_extras.RandomHorizontalFlip 
      prob: 0.5
      keys: ["image","mask"]
    - _target_: src.common.transforms.monai_extras.RandomAffine
      prob: 0.6
      keys: ["image","mask"]
      scale: [0.8, 1.2]
      degrees: [-15,15]
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image","mask"]
    