stochastic_weight_averaging:
  _target_: lightning.pytorch.callbacks.StochasticWeightAveraging
  swa_epoch_start: 0.75
  swa_lrs: 0.1
  annealing_epochs: 10 # TODO: Set this to last 0.25 of epochs
  annealing_strategy: "cos"

