# @package model.criterion
_target_: src.common.nn_modules.losses.combined_loss_diff_input.CombinedLossDiffInput
losses:
  lung_label : 
    _target_: monai.losses.GeneralizedDiceFocalLoss
    to_onehot_y: true
    softmax: true
    include_background: true
    lambda_gdl: 2
    lambda_focal: 5
    focal_weight: [2,4,4]
  lobe_label :
    _target_: monai.losses.GeneralizedDiceFocalLoss
    to_onehot_y: true
    softmax: true
    include_background: true
    lambda_gdl: 2
    lambda_focal: 5
    focal_weight: [1,4,4,5,8,5]
  combined : 
    _target_: src.common.nn_modules.losses.lung_lobe_loss.CombinedLungLobeLoss
    activation: 
      _target_: torch.nn.Softmax
      dim: 1
loss_inputs: 
  lung_label : lung_label
  lobe_label : lobe_label
  combined :
    - lung_label
    - lobe_label
  # lung_label : 
  #   _target_: src.common.nn_modules.losses.boundary_dice_focal_loss.BoundaryDiceFocalLoss
  #   factor_voxels_inside_boundary: 1.0
  #   factor_voxels_on_boundary: 1.0
  #   factor_voxels_outside_boundary: 0.0
  #   kwargs:
  #     lambda_dice: 2.0
  #     lambda_focal: 1.0
  #     include_background: true
  #     to_onehot_y: true
  #     softmax: true
  # lobe_label :
  #   _target_: src.common.nn_modules.losses.boundary_dice_focal_loss.BoundaryDiceFocalLoss
  #   factor_voxels_inside_boundary: 1.0
  #   factor_voxels_on_boundary: 1.0
  #   factor_voxels_outside_boundary: 0.0
  #   kwargs:
  #     lambda_dice: 2.0
  #     lambda_focal: 1.0
  #     include_background: true
  #     to_onehot_y: true
  #     softmax: true
weights:
  lung_label : 1
  lobe_label : 4
  combined : 5
activations: 
  lung_label : 
    _target_: torch.nn.Identity
  lobe_label : 
    _target_: torch.nn.Identity
  combined: 
    _target_: torch.nn.Identity