# @package model.criterion
_target_: src.common.nn_modules.losses.knowledge_distillation_loss.KD
alpha : 0
temperature : 1
losses : 
  _target_: monai.losses.GeneralizedDiceFocalLoss
  to_onehot_y: true
  softmax: true
  include_background: True
  lambda_gdl: 2
  lambda_focal: 4
  focal_weight: [4,5]
  # _target_: src.common.nn_modules.losses.spatial_weighted_loss.SpatialWeightedLoss
  # weights : [2,4]
  # roi_mask_keys : [icv_mask, falx]
  # loss : 
  #   _target_: monai.losses.GeneralizedDiceFocalLoss
  #   to_onehot_y: true
  #   softmax: true
  #   include_background: false
  #   lambda_gdl: 2
  #   lambda_focal: 4
  #   focal_weight: [3]
