model_cfg:
  spatial_dims: 3
fpn_params:
  returned_layers:
  - 1
  - 2
backbone:
  _target_: monai.networks.nets.resnet.resnet10
  spatial_dims: ${model_cfg.spatial_dims}
  conv1_t_stride:
  - 2
  - 2
  - 1
  pretrained: false
  progress: false
  n_input_channels: 3
  conv1_t_size:
  - 7
  - 7
  - 7
fe:
  _target_: monai.apps.detection.networks.retinanet_network.resnet_fpn_feature_extractor
  backbone: ${backbone}
  spatial_dims: ${model_cfg.spatial_dims}
  pretrained_backbone: false
  trainable_backbone_layers: null
  returned_layers: ${fpn_params.returned_layers}
anchor_params:
  _target_: voxdet.anchors.AnchorGeneratorBasedonStride
  strides:
  - - 2
    - 4
    - 4
  - - 4
    - 8
    - 8
  - - 8
    - 16
    - 16
classes:
- nodule
train_cfg:
  matcher:
    name: set_atss_matcher
    attr:
      num_candidates: 12
      center_in_gt: false
  sampler:
    name: set_hard_negative_sampler
    attr:
      batch_size_per_image: 500
      positive_fraction: 0.15
      min_neg: 400
      pool_size: 40
  reg_loss:
    box_loss:
      _target_: voxdet.bbox_func.reg_loss.RegLoss
      iou_loss: diou
      l1_loss: false
      reduction: mean
    encode_gt: false
    decode_pred: true
  cls_loss: ''
loss_weight: auto
