# @package model.net
# Not all arguments are updated here
_target_: src.common.nn_modules.nets.attn_unet.AttentionUnet
spatial_dims: 3
in_channels: 1
out_channels: 2
dropout: 0.1
channels: [16, 32, 64, 128, 256]
strides: [2, 2, 2, 2]
