# @package model.net
_target_: src.common.nn_modules.nets.segmentation.timm_models.TimmSegModel
in_channels: 3
num_classes: 2
label_keys: mask
n_blocks: 5
decoder_channels: [256,128, 64, 32, 16]
backbone: resnet18
segtype: unet
drop_rate: 0.4
drop_path_rate: 0.4
spatial_dims: 2
pretrained: True