_target_: src.common.nn_modules.nets.segmentation.unet3D.SmpUnet3DModel
num_classes: 
  - 6
  - 3
in_channels: 3
backbone: resnet18_3D
decoder_channels: [256, 128, 64, 32, 16]
n_blocks: 5
use_batchnorm: true
attention_type: scse_3D