_target_: src.models.videomae_module.VideoMAEModule
defaults:
  - optimizer: sgd
  - scheduler: one_cycle_lr
image_size: 32
tubelet_size: 2
num_channels: 3
num_frames: 8
patch_size: 4
mask_percentage: 0.75