_target_: src.models.combined_module.CombinedLitModule
defaults:
  - optimizer: sgd
  - scheduler: reduce_lr_plateau
  - net/segmentation: pls_net
  - criterion/segmentation: generalized_dice_focal_loss
activation: 
  _target_: torch.nn.Softmax
  dim: 1
metric: 
  _target_: src.metrics.segmentation.dice.Dice3D

# In the List[Dict] returned by the data extraction function. What is the key name which have the image batch
image_key: image
# In the List[Dict] returned by the data extraction function. What is the key name which have the label (GT mask) batch
label_keys: lobe_label
# In the List[Dict] returned by the data extraction function. What additional data we need to send to the model.
# Note that we need to have the same key name(`roi_mask`) in the dict from the extraction function and the
# parameter name in the model.
additional_keys: null
subgroups_keys: null
