_target_: src.models.sam3d_module.SAM3DModule
model : 
  _target_: src.common.nn_modules.nets.segment_anything.sam3D.Sam3D
  image_encoder: 
    _target_: src.common.nn_modules.nets.segment_anything.image_encoder3D.ImageEncoderViT3D
    img_size: 128
    patch_size:  16
    in_chans:  1
    out_chans: 384
    embed_dim:  768
    depth:  12
    num_heads:  12
    # mlp_ratio: 4.0
    # out_chans:  256
    # qkv_bias:  True
    # use_abs_pos:  True
    # use_rel_pos:  False
    # rel_pos_zero_init:  True
    global_attn_indexes: [2, 5, 8, 11]
    window_size:  14
  prompt_encoder: 
    _target_: src.common.nn_modules.nets.segment_anything.prompt_encoder3D.PromptEncoder3D
    embed_dim: 384
    image_embedding_size: [8,8,8]
    input_image_size: [128,128,128]
    mask_in_chans: 16
  mask_decoder: 
    _target_: src.common.nn_modules.nets.segment_anything.mask_decoder3D.MaskDecoder3D
    transformer_dim: 384
    num_multimask_outputs:  3
    iou_head_depth:  3
    iou_head_hidden_dim:  256
  pixel_mean: 
  pixel_std:

defaults:
  - optimizer: sgd
  - scheduler: one_cycle_lr