# @package model.metric
- _target_: torchmetrics.Accuracy
  task: "multiclass"
  num_classes: 2
- _target_: src.metrics.classification.auc.AUC
  num_classes: 2
- _target_: torchmetrics.Recall
  task: "multiclass"
  average: "macro"
  num_classes: 2