# @package model.net
_target_: src.common.nn_modules.nets.segmentation.Qnet.Qnet
num_classes: 2
# make sure that `encoder_channels` and `decoder_channels` number of blocks are 6 and 4 respectively.
encoder_channels: [1, 16, 32, 64, 128, 256]
decoder_channels: [128, 64, 32, 16]
