defaults:
  - transforms: bleed_seg_test
  - analysis: null
  - _self_

_target_: src.datamodules.base_dataloader.MetaClsDataModule
data_cfg:
  train:
    data_extract_func: ich_seg_data_loader_csv
    csv_path: [/home/users/shubham.kumar/projects/ICH_classification_segmentation/ICH_dataset_train.csv]
    sample_frac: 1
  val:
    data_extract_func: ich_seg_data_loader_csv
    csv_path: [/home/users/shubham.kumar/projects/ICH_classification_segmentation/ICH_dataset_val_modified_seg.csv]
    sample_frac: 1
  test:
    data_extract_func: ich_seg_data_loader_csv
    csv_path : ["/home/users/shubham.kumar/projects/ICH_classification_segmentation/qquantFDA_qure25k.csv",
                "/home/users/shubham.kumar/projects/ICH_classification_segmentation/ICH_dataset_test_neg_seg.csv"]
    sample_frac: 1
  oversample_ratios: null
dataloader_cfg:
  batch_size: 1
  num_workers: 4
  sample : False
  sample_fusion: False
  frac_without_mask: 0
  num_samples : 10000
  drop_last: False
  frac_per_class: 
    SDH : 0.3
    IPH : 0.1
    SAH : 0.25
    EDH : 0.25
    IVH : 0.1