defaults:
  - transforms: bleed_cls_fusion_transforms_old
  - analysis: null
  - _self_

_target_: src.datamodules.base_dataloader.MetaClsDataModule
data_cfg:
  train:
    data_extract_func: ich_cls_data_loader_csv
    # csv_path : [/home/users/shubham.kumar/projects/ICH_classification_segmentation/ich_bleed_data/slicewise_train_gts.csv]
    csv_path: [/home/users/shubham.kumar/projects/ICH_classification_segmentation/ICH_dataset_train.csv]
    sample_frac: 1
    # num_samples_per_class: 200
    # frac_per_class: 
    #   SDH : 0.4
    #   IPH : 0.15
    #   SAH : 0.15
    #   EDH : 0.15
    #   IVH : 0.15
  val:
    data_extract_func: ich_cls_data_loader_csv
    # csv_path : [/home/users/shubham.kumar/projects/ICH_classification_segmentation/ich_bleed_data/slicewise_val_gts.csv]
    csv_path: [/home/users/shubham.kumar/projects/ICH_classification_segmentation/ICH_dataset_val_modified.csv]
    # csv_path: [/home/users/shubham.kumar/projects/ICH_classification_segmentation/ICH_dataset_val.csv]
    sample_frac: 1
    # num_samples_per_class: 100
    # frac_per_class: 
    #   SDH : 0.4
    #   IPH : 0.15
    #   SAH : 0.15
    #   EDH : 0.15
    #   IVH : 0.15
  test:
    data_extract_func: ich_cls_data_loader_csv
    csv_path : [/home/users/shubham.kumar/projects/ICH_classification_segmentation/ich_bleed_data/data_full_ich_test_nas3.csv]
    sample_frac: 1
  oversample_ratios: null
dataloader_cfg:
  batch_size: 6
  num_workers: 12
  sample : False
  sample_fusion: True
  frac_without_mask: 0.5
  num_samples : 10000
  drop_last: False
  frac_per_class: 
    SDH : 0.3
    IPH : 0.1
    SAH : 0.25
    EDH : 0.25
    IVH : 0.1

  #   > 4,12 > 8,16 > 4,8 ~= 4,16

