defaults:
  - transforms: fpr_sl_transforms
  - analysis: null
  - _self_
_target_: src.datamodules.base_dataloader.MetaClsDataModule
data_cfg:
  data_extract_func: fpr_sl_data_loader
  neg_csvs: 
  - /home/users/shubham.kumar/projects/qct_training_framework/notebooks/lidc_fpr_sl.csv
  - /home/users/shubham.kumar/projects/qct_training_framework/notebooks/nlst_fpr_sl.csv
  pos_csvs:
  - /home/users/shubham.kumar/projects/fpr/lidc_nodules_bbox.csv
  - /home/users/shubham.kumar/projects/fpr/nlst_nodules_bbox.csv
  neg_directorys: 
  - /cache/fast_data_nas8/qct/shubham/fpr_sam3d_cache/lidc
  - /cache/fast_data_nas8/qct/shubham/fpr_sam3d_cache/nlst
  pos_directorys:
  - /cache/fast_data_nas8/qct/shubham/fpr_sam3d_cache/lidc
  - /cache/fast_data_nas8/qct/shubham/fpr_sam3d_cache/nlst
  frac : 1
  oversample_ratios: null
dataloader_cfg:
  batch_size: 32
  num_workers: 16
  sample: False 
  sample_fusion: False
  balanced_sample: True