defaults:
  - transforms: segm_tf
  - analysis: null
  - _self_

_target_: src.datamodules.base_dataloader.MetaClsDataModule
data_cfg:
  data_extract_func: lung_segmentation_data_loader
  csvs:
    - /home/users/shubham.kumar/projects/lung_lobe_segmentation/lung_lobe_cct_data.csv
    - /home/users/shubham.kumar/projects/lung_lobe_segmentation/LCTSC_dataset.csv
    - /home/users/shubham.kumar/projects/lung_lobe_segmentation/LOLA_dataset.csv
    - /home/users/shubham.kumar/projects/lung_lobe_segmentation/LIDC_dataset.csv
    - /home/users/shubham.kumar/projects/lung_lobe_segmentation/NLST_dataset.csv
    - /home/users/shubham.kumar/projects/lung_lobe_segmentation/VESSEL12_dataset.csv
    - /home/users/shubham.kumar/projects/lung_lobe_segmentation/RAD_CHEST_dataset.csv
  load_scan: True
  # use when load_scan is True
  # data_root:
  #   - {image: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/qsc/, lung_annot: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/qsc_lung_mask/ , lobe_annot: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/qsc_lobe_mask/}
  #   - {image: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/lctsc/, lung_annot: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/lctsc_lung_mask/ , lobe_annot: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/lctsc_lobe_mask/}
  #   - {image: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/lola/, lung_annot: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/lola_lung_mask/ , lobe_annot: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/lola_lobe_mask/}
  #   - {image: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/lidc/, lung_annot: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/lidc_lung_mask/ , lobe_annot: /cache/fast_data_nas8/qct/lung_lobe_seg_cache/lidc_lobe_mask/}
  # ext: [.nii.gz, .nii.gz, .mha, .nii.gz]

  # use when dataset = "dcm"
  # data_root:
  #   - {image: /cache/fast_data_nas72/qsc/, lung_annot: /cache/fast_data_nas72/lung_lobe_segmentation/lung_mask_cache/ , lobe_annot: /cache/fast_data_nas72/lung_lobe_segmentation/lobe_mask_cache/}
  #   - {image: /cache/fast_data_nas72/lung_lobe_segmentation/lctsc_scan_cache, lung_annot: /cache/fast_data_nas72/lung_lobe_segmentation/lctsc_lung_mask_cache/ , lobe_annot: /cache/fast_data_nas72/lung_lobe_segmentation/lctsc_lobe_mask_cache/}
  #   - {image: /cache/fast_data_nas72/lung_lobe_segmentation/lola_scan_cache, lung_annot: /cache/fast_data_nas72/lung_lobe_segmentation/lola_lung_mask_cache/ , lobe_annot: /cache/fast_data_nas72/lung_lobe_segmentation/lola_lobe_mask_cache/}
  #   - {image: /cache/fast_data_nas72/lung_lobe_segmentation/lidc_scan_cache, lung_annot: /cache/fast_data_nas72/lung_lobe_segmentation/lidc_lung_mask_cache/ , lobe_annot: /cache/fast_data_nas72/lung_lobe_segmentation/lidc_lobe_mask_cache/}

  # use when dataset = "hdf5"
  data_root:
    - { image: /cache/fast_data_nas8/qct/shubham/lung_lobe_seg_cache/hdf5_cache/qsc }
    - { image: /cache/fast_data_nas8/qct/shubham/lung_lobe_seg_cache/hdf5_cache/lctsc }
    - { image: /cache/fast_data_nas8/qct/shubham/lung_lobe_seg_cache/hdf5_cache/lola }
    - { image: /cache/fast_data_nas8/qct/shubham/lung_lobe_seg_cache/hdf5_cache/lidc }
    - { image: /cache/fast_data_nas8/qct/shubham/lung_lobe_seg_cache/hdf5_cache/nlst }
    - { image: /cache/fast_data_nas8/qct/shubham/lung_lobe_seg_cache/hdf5_cache/vessel12}
    - { image: /cache/fast_data_nas8/qct/shubham/lung_lobe_seg_cache/hdf5_cache/rad_chest} 

  sample_size: null
  sample_frac:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
  dataset: hdf5
  invert_scan: [True, False, False, False, False, True, False]
  random_state: 445
  num_slices_per_volume: 32
  stride: 0
  keep_lung_only: False ## If True, only keep the lung region , make it False when loading whole scan at once
  oversample_ratios: null
dataloader_cfg:
  batch_size: 2
  num_workers: 8
  sample: False
  sample_fusion: False
