defaults:
  - transforms: fpr_sl_mae_transforms
  - analysis: null
  - _self_
_target_: src.datamodules.base_dataloader.MetaClsDataModule
data_cfg:
  data_extract_func: fpr_sl_mae_data_loader
  mae_inputs : 
    csvs: 
    # - /home/users/shubham.kumar/projects/qct_training_framework/notebooks/fpr_lidc_frac_03.csv
    # - /home/users/shubham.kumar/projects/qct_training_framework/notebooks/fpr_nlst_pm_t0.csv
    - /home/users/shubham.kumar/projects/qct_training_framework/notebooks/fpr_wcg.csv
    - /home/users/shubham.kumar/projects/qct_training_framework/notebooks/fpr_qidw.csv
    - /home/users/shubham.kumar/projects/qct_training_framework/notebooks/fpr_qure_external_v1.csv
    directorys: 
    # - /cache/fast_data_nas8/qct/shubham/fpr_cache_48_48_16/safetensors_cache/
    # - /cache/fast_data_nas8/qct/shubham/fpr_cache_nlst_pm_t0/
    - /cache/fast_data_nas8/qct/shubham/fpr_cache_wcg/
    - /cache/fast_data_nas8/qct/shubham/fpr_cache_qidw/
    - /cache/fast_data_nas8/qct/shubham/fpr_cache_qure_external_v1/
    data_source :
    # - lidc_luna
    # - nlst_pm_t0
    - wcg
    - qidw
    - qure_external_v1
    frac : 1
  sl_inputs :
    neg_csvs: 
    - /home/users/shubham.kumar/projects/qct_training_framework/notebooks/lidc_fpr_sl.csv
    - /home/users/shubham.kumar/projects/qct_training_framework/notebooks/nlst_fpr_sl.csv
    pos_csvs: 
    - /home/users/shubham.kumar/projects/fpr/lidc_nodules_bbox.csv
    - /home/users/shubham.kumar/projects/fpr/nlst_nodules_bbox.csv
    neg_directorys: 
    - /cache/fast_data_nas8/qct/shubham/fpr_sam3d_cache/lidc
    - /cache/fast_data_nas8/qct/shubham/fpr_sam3d_cache/nlst
    pos_directorys: 
    - /cache/fast_data_nas8/qct/shubham/fpr_sam3d_cache/lidc
    - /cache/fast_data_nas8/qct/shubham/fpr_sam3d_cache/nlst
    data_source :
    - lidc
    - nlst
    frac : 1
  oversample_ratios: 
    0 : 1
    1 : 10 
dataloader_cfg:
  batch_size: 128
  num_workers: 16
  sample: False 
  sample_fusion: False
  balanced_sample: True