defaults:
  - transforms: segm_lung_lobe_transforms
  - analysis: null
  - _self_

_target_: src.datamodules.base_dataloader.MetaClsDataModule
data_cfg:
  data_extract_func: mca_lvo_data_loader
  csvs:
    - /cache/fast_data_nas8/qer/shubham/mca_lvo/mca_lvo_dev_dataset.csv
  data_root:
    - { raw: /cache/fast_data_nas8/qer/shubham/mca_lvo/raw/ }
    - { tilt_corr: /cache/fast_data_nas8/qer/shubham/mca_lvo/tilt_corr/ }
  sample_size: null
  sample_frac:
    - 1
    - 1
  random_state: 445
  oversample_ratios: null
dataloader_cfg:
  batch_size: 2
  num_workers: 8
