defaults:
  - transforms: cls_transforms
  - analysis: lung_nodules
  - _self_

_target_: src.datamodules.base_dataloader.MetaClsDataModule
data_cfg:
  characteritic_type: Texture # Spiculation/Calcification
  train:
    - data_extract_func: lung_nodule_cls_data_loader
      srcs_key: src
      data_srcs: ["lidc"]
      csvs:
        - /home/users/souvik.mandal/datasets/data_v1.4/lidc/lidc_data_splits/val/0.csv
  val:
    # -
    #   data_extract_func: lung_nodule_classification_ctloader_dataloader
    #   data_root: /cache/datanas1/qct-nodules/nifti_with_annots/lidc
    #   srcs_key: ds_name
    #   data_srcs: ["lidc"]
    #   meta_cfg: ${....analysis}
    #   csvs:
    #     - /home/users/vanapalli.prakash/repos/qct_nodule_detection/data1.3.4/v001/folds/bucket_0.csv
    - data_extract_func: lung_nodule_cls_data_loader
      srcs_key: src
      data_srcs: ["lidc"]
      csvs:
        - /home/users/souvik.mandal/datasets/data_v1.4/lidc/lidc_data_splits/val/0.csv
  test:
    # -
    #   data_extract_func: lung_nodule_classification_ctloader_dataloader
    #   data_root: /cache/datanas1/qct-nodules/nifti_with_annots/lidc
    #   srcs_key: ds_name
    #   data_srcs: ["lidc"]
    #   meta_cfg: ${....analysis}
    #   csvs:
    #     - /home/users/vanapalli.prakash/repos/qct_nodule_detection/data1.3.4/v001/folds/bucket_0.csv
    - data_extract_func: lung_nodule_cls_data_loader
      srcs_key: src
      data_srcs: ["lidc"]
      csvs:
        - /home/users/souvik.mandal/datasets/data_v1.4/lidc/lidc_data_splits/val/0.csv
  cls2idx_dict:
    Texture:
      Non-Solid/GGO: 2
      non-Solid/Mixed: 2
      Non-Solid/Mixed: 2
      Solid: 0
      solid: 0
      Part Solid/Mixed: 1
      Solid/Mixed: 1
    Calcification:
      calcification_absent: 0
      calcification_present: 1
    Spiculation:
      # two class for Spiculation (spiculation_no/spiculation_yes (marked and medium margin are here))
      # Dr Nikhith : spiculation_medium should be in yes category.
      spiculation_no: 0
      spiculation_yes: 1
  oversample_ratios: # repeats the dataset
    0: 1
    1: 2
    2: 2
  # label_key: which key to used for sampling. Check loader transforms to get all the metadata available.
  # we can do sampling based on metadata also like z-spacing, volume...
  label_key: label

  # sample_weights_cfg: # Sampling method
  # type: src
  # weights: # If type==src and weights is None won't do any sampling.
  #   lidc: 2
  # type: single_class
  # weights: # None to auto generate sampling ratio based on the nodule frequency
  #   0: 1
  #   1: 2
  #   2: 2.5
dataloader_cfg:
  batch_size: 4
  num_workers: 4
