# Val transforms if test transforms is not mentioned
# use the val transforms as test transforms
val_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image","mask"]
    - _target_: src.common.transforms.monai_extras.FixedZDim
      keys: ["image", "mask"]
      target_z: 32
      pad_value: 0
      random_center_crop: False
    - _target_ : src.common.transforms.monai_extras.CropHeadCT
      image_key: "image"
      mask_keys: ["mask"]
    # - _target_ : src.common.transforms.monai_extras.ApplyCrop
    #   keys: ["image","mask"]
    #   crop_key: crop
    - _target_ : src.common.transforms.monai_extras.BinarizeSegMask
      keys: ["mask"]
    - _target_: src.common.transforms.monai_extras.ResizeImage
      keys: ["image","mask"]
      size: [224,224]
      interpolation: 
        image: bicubic
        mask: nearest
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["brain_window","blood_window","bone_window"]
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image","mask"]
      
# train transforms
train_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image","mask"]
    - _target_: src.common.transforms.monai_extras.FixedZDim
      keys: ["image", "mask"]
      target_z: 32
      pad_value: 0
      random_center_crop: False
    - _target_ : src.common.transforms.monai_extras.ApplyCrop
      keys: ["image","mask"]
      crop_key: crop
    - _target_ : src.common.transforms.monai_extras.BinarizeSegMask
      keys: ["mask"]
    - _target_: src.common.transforms.monai_extras.ResizeImage
      size: [224,224]
      keys: ["image", "mask"]
      interpolation: 
        image: bicubic
        mask: nearest
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["brain_window","blood_window","bone_window"]
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image","mask"]