# Val transforms if test transforms is not mentioned
# use the val transforms as test transforms
val_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadSafeTensor
      image_key: image
    # - _target_: src.common.transforms.monai_extras.CropTensor
    #   output_shape: [8,32,32]
    #   key: image
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["LungA"]
      
# train transforms
train_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadSafeTensor
      image_key: image
    # - _target_: src.common.transforms.monai_extras.CropTensor
    #   output_shape: [8,32,32]
    #   key: image
    - _target_: src.common.transforms.monai_extras.ApplyWindowsChannelWise
      keys: ["image"]
      windows: ["LungA"]
    - _target_: src.common.transforms.monai_extras.RandomHorizontalFlip
      keys: ["image"]
      prob: 0.5
    - _target_ : src.common.transforms.monai_extras.RandomGaussianBlur
      keys: ["image"]
      kernel_size: 3
      sigma: [0.1, 2.0]
      prob: 0.5