# Val transforms if test transforms is not mentioned
# use the val transforms as test transforms
val_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image", "label" , "mask"]
    - _target_: src.common.transforms.monai_extras.ResizeImage
      keys: ["image", "mask"]
      size: [224,224]
      interpolation: 
        image: bicubic
        mask: nearest    
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image"]

# train transforms
train_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image", "label", "mask"]
    - _target_: src.common.transforms.monai_extras.ResizeImage
      size: [224,224]
      keys: ["image"]
      interpolation: 
        image: bicubic
        mask: nearest
    - _target_: src.common.transforms.monai_extras.RandomAffine
      prob: 0.6
      keys: ["image", "mask"]
      scale: [0.8, 1.1]
      degrees: [-15,15]
    
    - _target_: src.common.transforms.monai_extras.ExpandDim
      keys: ["image"]