# Val transforms if test transforms is not mentioned
# use the val transforms as test transforms
val_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image" , "lung_label"]

# train transforms
train_transforms:
  _target_: monai.transforms.Compose
  transforms:
    - _target_: src.common.transforms.monai_extras.LoadHDF5Data
      keys: ["image" , "lung_label"]