# @package model.net
_target_: src.common.nn_modules.nets.mae.mae3d_classification.ViTMAEForImageClassification
# model_ckpt: /data_nas5/qer/shubham/mae3d_checkpoints/fpr_mae/runs/2023-11-14_11-44-42/checkpoints/epoch=219_step=115500_val_loss=0.65.ckpt
# model: 
#   _target_: src.common.nn_modules.nets.mae.mae3d.MAE3D
#   pos_embed_type: sincos
#   mask_ratio: 0.7
#   input_size: [48, 48, 16]
#   patch_size: [6, 6, 4]
#   in_chans: 1
#   encoder_embed_dim: 768
#   encoder_depth: 6
#   encoder_num_heads: 12
#   decoder_embed_dim: 384
#   decoder_depth: 4
#   decoder_num_heads: 12

# model_ckpt: /data_nas5/qer/shubham/mae3d_checkpoints/fpr_mae/runs/2023-11-15_10-15-31/checkpoints/epoch=127_step=67200_val_loss=0.65.ckpt
# model: 
#   _target_: src.common.nn_modules.nets.mae.mae3d.MAE3D
#   pos_embed_type: sincos
#   mask_ratio: 0.7
#   input_size: [48, 48, 16]
#   patch_size: [6, 6, 4]
#   in_chans: 1
#   encoder_embed_dim: 576
#   encoder_depth: 6
#   encoder_num_heads: 12
#   decoder_embed_dim: 384
#   decoder_depth: 4
#   decoder_num_heads: 12

#v4
# model_ckpt: /data_nas5/qer/shubham/mae3d_checkpoints/fpr_mae/runs/2023-12-20_21-59-56/checkpoints/epoch=123_step=27528_val_loss=0.01.ckpt
# model: 
#   _target_: src.common.nn_modules.nets.mae.mae3d.MAE3D
#   pos_embed_type: sincos
#   mask_ratio: 0.7
#   input_size: [48, 48, 16]
#   patch_size: [6, 6, 4]
#   in_chans: 1
#   encoder_embed_dim: 768
#   encoder_depth: 4
#   encoder_num_heads: 12
#   decoder_embed_dim: 384
#   decoder_depth: 4
#   decoder_num_heads: 12
#   encoder_drop_rate: 0.1


# v5
model_ckpt: /data_nas5/qer/shubham/mae3d_checkpoints/fpr_mae/runs/2023-12-20_20-17-17/checkpoints/epoch=75_step=8436_val_loss=0.01.ckpt
model: 
  _target_: src.common.nn_modules.nets.mae.mae3d.MAE3D
  pos_embed_type: sincos
  mask_ratio: 0.7
  input_size: [48, 48, 16]
  patch_size: [6, 6, 4]
  in_chans: 1
  encoder_embed_dim: 576
  encoder_depth: 4
  encoder_num_heads: 12
  decoder_embed_dim: 252
  decoder_depth: 3
  decoder_num_heads: 12
  encoder_drop_rate: 0.15
  attn_drop_rate: 0.1
