testing_csv: "/models_common_e2e/cxr_data/testing/csvs/testing_master_updated_new_tb_added_2024_06_24_corrected.csv"
testing_images: "/cache/fast_data94/ChestXRays/alldata/testing/pngs_1440/"
testing_annotation_path: "/cache/fast_data_nas6/cxr/cxr_data/test_annotations/"
