# @package model.net 
_target_: src.common.nn_modules.nets.slicewise.multitask.MultiTaskFusionNet
backbone: seresnext50_32x4d
num_classes: 2
n_blocks: 5
segtype: unet
pretrained: True
drop_rate: 0.3
drop_path_rate: 0.3
in_channels: 3
decoder_channels: [256, 128, 64, 32, 16]
attention_type: scse
cls_pooling: avg
cls_dropout: 0.2
