# @package model.net 
# _target_: src.common.nn_modules.nets.slicewise.slicelabels.SliceWise
# backbone: seresnext50_32x4d
# drop_rate : 0.4
# in_chans: 3
# num_classes: 2
# global_pool: avg

_target_: src.common.nn_modules.nets.slicewise.v3_slicelabels.V3Net
in_chans: 2
decoder_attention_type: scse
cls_pooling: avg
cls_dropout: 0.4

