sampling_tags: ['solitary', 'cancer']
heads:  ['solitary', 'cancer']
user_class_wts: {'tinynodule': 1, 'cancer': 1}
loss_wts: [1, 1]
alpha: 6

# peffusion: 5.0
#       opacity: 3.0
#       fibrosis: 3.0
#       atelectasis: 5.0
#       consolidation: 3.0
#       nodule: 5.0
#       calcification: 3.0
#       ribfracture: 5.0
#       pneumothorax: 5.0
#       mass: 5.0
#       mediastinal_mass: 5.0

