## modified nota weights chanegd model changed seg - loss weights  and user  class weights acc to masks available , cls/seg =1/3
defaults:
  # - cls: cls_tb
  # - seg: seg_tb
  # - files: e2e
  # - model/optimizer: adama
  # - model/scheduler: one_cycle_lr
  - override hydra/hydra_logging: disabled #prevent logging
  - override hydra/job_logging: disabled #prevent logging
  - _self_

#prevent logging
hydra:
  output_subdir: null
  run:
    dir: .

path:
  checkpoint_dir: "/raid/qxr_ln_trainings/checkpoints"
  checkpoint_path: ""
  log_directory: "/raid/qxr_ln_trainings/logs"


cls:
    sampling_tags: ['nodule', 'normal', 'nota', 'homogenous', 'inhomogenous', 'diffused_nodule', 'regular_border', 'irregular_border']
    heads: ['nodule', 'normal' , 'homogenous', 'inhomogenous', 'diffused_nodule', 'regular_border', 'irregular_border']
    user_class_wts: {"nodule": 1, "nota": 2, "normal": 2, "homogenous": 0.25, "inhomogenous": 0.25, "diffused_nodule": 0.25, "regular_border": 0.25, "irregular_border": 0.25}
    loss_wts : {"nodule": 2, "normal": 1, "homogenous": 2, "inhomogenous": 2, "diffused_nodule": 2, "regular_border": 2, "irregular_border": 2}
    alpha: 1

seg:
    sampling_tags: ['nodule', 'homogenous', 'inhomogenous', 'diffused_nodule', 'regular_border', 'irregular_border']
    heads: ['nodule', 'homogenous', 'inhomogenous', 'diffused_nodule', 'regular_border', 'irregular_border']
    dice_threshold: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
    user_class_wts : {'nodule': 2.0,'homogenous': 1.0, 'inhomogenous': 1.0, 'diffused_nodule': 2.0, 'regular_border': 1.0, 'irregular_border': 1.0}
    loss_wts : {'nodule': 2.0, 'homogenous': 2.0, 'inhomogenous': 2.0, 'diffused_nodule': 2.0, 'regular_border': 2.0, 'irregular_border': 2.0}
    alpha: 1.0


files:
  ground_truth_csv: '/raid/training_csvs/9_sep_2M_diffused_col_complete_data.csv'
  img_folder_path:  [
    '/raid/qxr_ln_training_data/cxr_data/training/images',
    '/raid/qxr_ln_training_data/fake_data_2d/fake_imgs/',
    ]
  annotation_path: [
    '/raid/qxr_ln_training_data/cxr_data/training/annotations/lms_annotations',
    '/raid/qxr_ln_training_data/fake_data_2d/fake_masks',
    ]


model:
  __target__: cxr_training.nnmodule.nnmodule_controller.LitModel
  encoder_library: smp
  encoder: tu-tf_efficientnetv2_m_in21ft1k
  decoder: UnetPlusPlus
  load_prt: true
  pretrained_ckpt: /raid/qxr_ln_trainings/checkpoints/base_training/7_sept_effnet_unetplusplus_old_data_manoj_lr_0.2_v1/model_1600-epoch=227-val_loss=3.758750.ckpt
  in_channels: 1
  out_channels: 2
  scheduler:
    _target_: torch.optim.lr_scheduler.OneCycleLR
    params:
      pct_start: 0.3
      max_lr: 0.1
      anneal_strategy: cos
      div_factor: 25
      steps_per_epoch: 1,
      epochs: initial_stage_epochs
  optimizer:
    _target_: torch.optim.SGD
    params:
      lr: 0.1
      weight_decay: 0.0001


trainer:
  description: base_training
  project: qxr_ln_training
  model_file: 9_sept_effnet_unetplusplus_prt_full_data_diffused_head
  check_gradients: false
  recipe_module: cxr_training.recipes.base_recipe.BaseRecipe
  recipe: cls_seg
  total_epochs: 200
  accumulate_grad_batches: 6
  strategy: ddp
  batch_size: 8
  precision: 16
  num_workers: 8
  train_samples: 16000
  validation_samples: 8000
  gpus: [-1]
  fast_dev_run: false
params:
  data_loader: cxr_training.data.dataloader.base_dataloader.DataModule
  dataset_type: cxr_training.data.datasets.cls_seg_dataset.Base_dataset
  metric_type: default
  im_size: 1024
  loss_type: dice-bce
  sources: []
  equal_source_sampling: false
  mask_threshold: 0.2
  use_real_fake_sampling: true
  real_data_wts: 0.3
  use_3d_2d_fake_data_sampling: False
  data_weights_3d: 0.3
  sampler: train_weighted_val_random


use_clearml: True
validate_config: False