defaults:
  # - cls: cls_tb
  # - seg: seg_tb
  # - files: e2e
  # - model/optimizer: adam
  # - model/scheduler: one_cycle_lr
  - override hydra/hydra_logging: disabled #prevent logging
  - override hydra/job_logging: disabled #prevent logging
  - _self_

#prevent logging
hydra:
  output_subdir: null
  run:
    dir: .

path:
  checkpoint_dir: "/fast_data_e2e11/qxr_ln_trainings/checkpoints"
  checkpoint_path: ""
  log_directory: "/fast_data_e2e11/qxr_ln_trainings/logs"

cls: 
  sampling_tags: ['nodule', 'regular_border', 'irregular_border', 'homogenous', 'inhomogenous', 'normal', 'nota'] 
  heads: ['nodule', 'regular_border', 'irregular_border', 'homogenous', 'inhomogenous', 'normal']
  user_class_wts: {'nodule': 1, 'regular_border': 1, 'irregular_border': 1, 'homogenous': 1, 'inhomogenous': 1, 'normal': 1, 'nota': 1}
  loss_wts : {'nodule': 3.5344359498525493,
  'regular_border': 4.907476067486108,
  'irregular_border': 5.5816953044340165,
  'homogenous': 6.158857933115976,
  'inhomogenous': 5.992514407792055,
  'normal': 1.0}
  alpha: 1

seg:
  sampling_tags: ['nodule']
  heads: ['nodule']
  dice_threshold: [0.35, 0.35, 0.35, 0.35, 0.35] 
  user_class_wts: {'nodule': 1.0, 'regular_border': 1.0, 'irregular_border': 1.0, 'homogenous': 1.0, 'inhomogenous': 1.0} 
  loss_wts: {'nodule': 1.0,
  'regular_border': 1.3884750316923524,
  'irregular_border': 1.5792322689188567,
  'homogenous': 1.7425292240400942,
  'inhomogenous': 1.6954655545652348}
  alpha: 6

files:   
  testing_csv: '/fast_data_e2e11/qxr_ln_trainings/testing/nlst_jsrt.csv'
  testing_images:  ['/fast_data_e2e_1/cxr/qxr_ln_data/jsrt_nlst/data']
  testing_annotation_path: ['/fast_data_e2e_1/cxr/qxr_ln_data/jsrt_nlst/masks', '/models_common_e2e/cxr_data/testing/test_annotations']  ##giving a dummy path for now to avoid error

model:
  __target__: cxr_training.nnmodule.nnmodule_controller.LitModel
  encoder_library: timm
  encoder: swinv2_tiny_window8_256
  decoder: unetplusplus
  in_channels: 1
  out_channels: 2
  scheduler:
    _target_: torch.optim.lr_scheduler.OneCycleLR
    params:
      pct_start: 0.3
      max_lr: 0.0005
      anneal_strategy: 'cos'
      div_factor: 250 #self.max_lr / self.optimizer_lr
      final_div_factor: 100 # self.optimizer_lr / self.final_lr
      base_momentum: 0.90 # momentum changes beta[0] value in adamw
      max_momentum: 0.95
      three_phase: False
  optimizer:
    _target_: torch.optim.AdamW
    params:
      lr: 0.0005
      betas: [0.9, 0.99]
      eps: 1e-08
      weight_decay: 0.1

trainer:
    description: "base_training"
    project: "qxr_ln_training"
    model_file: "17_aug_swin_base_full_data"
    batch_size: 4
    num_workers: 4
    gpus: [0]
    recipe: "testing"
    recipe_module: cxr_training.recipes.test_recipe.TestRecipe
    checkpoint_dir: "/fast_data_e2e11/qxr_ln_trainings/checkpoints"
    model_list: ['model_1044-last.ckpt', 'model_1044-last-v1.ckpt']  #model_993-last-v3.ckpt model_1044-last.ckpt

params:
    im_size: 1024
    f1_beta_value:
    inference_on_subset: False
    inference_on_images: False
    inference_type: "cls_seg"
    metric_type: "cls_seg"
    inference_run: True
    metric_run: True

use_clearml: False
validate_config: Falsed











