## modified nota weights chanegd model changed seg - loss weights  and user  class weights acc to masks available , cls/seg =1/3
defaults:
  # - cls: cls_tb
  # - seg: seg_tb
  # - files: e2e
  # - model/optimizer: adama
  # - model/scheduler: one_cycle_lr
  - override hydra/hydra_logging: disabled #prevent logging
  - override hydra/job_logging: disabled #prevent logging
  - _self_

#prevent logging
hydra:
  output_subdir: null
  run:
    dir: .

path:
  checkpoint_dir: "/raid/qxr_ln_trainings/checkpoints"
  checkpoint_path: ""
  log_directory: "/raid/qxr_ln_trainings/logs"


cls: 
    sampling_tags: ["nodule", "solitary", 'normal', 'nota']
    heads: [ "nodule", "solitary"]
    user_class_wts: {"nodule": 1,  "solitary": 1, "normal": 1, "nota": 2}
    loss_wts : {'nodule': 2, 'solitary': 2}
    alpha: 1

seg:
    sampling_tags: [ 'nodule']
    heads: [ 'nodule']
    dice_threshold: [0.2]
    user_class_wts : {'nodule': 2}
    loss_wts : {'nodule': 2}
    alpha: 6
  

files:   
  ground_truth_csv: '/raid/piyush/training/training_csvs/old_train_data_1.8M.csv'
  img_folder_path:  ['/raid/cxr_data/training/images/']
  annotation_path: ['/raid/cxr_data/training/annotations/lms_annotations']


model:
  __target__: cxr_training.nnmodule.nnmodule_controller.LitModel
  encoder_library: smp
  encoder: tu-efficientnet_b5
  decoder: FPN
  in_channels: 1
  out_channels: 2
  scheduler:
    _target_: torch.optim.lr_scheduler.OneCycleLR
    params:
      pct_start: 0.3
      max_lr: 0.2
      anneal_strategy: cos
      div_factor: 25
      steps_per_epoch: 1 ,
      epochs: initial_stage_epochs
  optimizer:
    _target_: torch.optim.SGD
    params:
      lr: 0.2
      weight_decay: 0.0001


trainer:
  description: base_training
  project: qxr_ln_training
  model_file: 6_sep_manoj_model90_b52-epoch=155-val_solitary_new
  check_gradients: false
  recipe_module: cxr_training.recipes.base_recipe.BaseRecipe
  recipe: cls_seg
  total_epochs: 160
  accumulate_grad_batches: 2
  strategy: ddp
  batch_size: 16
  precision: 16
  num_workers: 8
  train_samples: 8000
  validation_samples: 1000
  gpus: [-1]
  fast_dev_run: false
params:
  data_loader: cxr_training.data.dataloader.base_dataloader.DataModule
  dataset_type: cxr_training.data.datasets.cls_seg_dataset.Base_dataset
  metric_type: default
  im_size: 960
  loss_type: dice-bce
  sources: []
  equal_source_sampling: false
  mask_threshold: 0.2
  use_real_fake_sampling: False
  real_data_wts: 0.7
  use_3d_2d_fake_data_sampling: False
  data_weights_3d: 0.3
  sampler: train_weighted_val_random


use_clearml: True
validate_config: False