defaults:
  - model_checkpoint
  # - early_stopping
  - learning_rate_monitor
  - stochastic_weight_averaging
  - model_summary
  - rich_progress_bar
  # - pred_logger
  # - seg_sub_analysis
  # - cls_sub_analysis
  - _self_ # Load all configs above and then merge the below. position of `_self_` makes the changes to defaults.

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/acc"
  mode: "max"
  save_last: True
  auto_insert_metric_name: True

# early_stopping:
#   monitor: "val/acc"
#   patience: 100
#   mode: "max"

model_summary:
  max_depth: -1
