_target_: src.models.combined_module.CombinedLitModule
defaults:
  - optimizer: sgd
  - scheduler: one_cycle_lr
  - criterion/segmentation: knowledge_distillation_loss.yaml
  - net/segmentation: multitaskfusion
activation: 
  _target_: torch.nn.Softmax
  dim: 1
metric: 
  _target_ : src.metrics.segmentation.dice.Dice3D
  num_classes: 2
  average: micro
  ignore_background: True
knowledge_distillation: True
additional_keys: null
subgroups_keys: null
image_key : image
label_keys : mask
