_target_: src.models.nodule_cls_module.TrainerClassifier
defaults:
  - optimizer: sgd
  - scheduler: one_cycle_lr
  - net/classification: timm_nets
  - criterion/classification: cross_entropy
  - metric: class_metrics
num_classes: 3
additional_keys:
  - roi_mask
subgroups_keys: [z_spacing, volume, Texture, Spiculation, Calcification]
# mix_up_cfg: # uncomment to use mix-up
#   mix_up_alpha: 0.0
