z_spacing:
  type: bin
  bins: [2, 4, 10]
Texture:
  type: mapping
  mappings:
    Non-Solid/GGO: 2
    non-Solid/Mixed: 2
    Non-Solid/Mixed: 2
    Solid: 0
    solid: 0
    Part Solid/Mixed: 1
    Solid/Mixed: 1
    # self mappings
    texture_non_solid: 2
    texture_solid: 0
    texture_part_solid: 1
Spiculation:
  type: mapping
  mappings:
    No Spiculation: 0
    Nearly No Spiculation: 0
    Medium Spiculation: 1
    Marked Spiculation: 1
    Near Marked Spiculation: 1
    near Marked Spiculation: 1
    near Sharp: 1

    # self mappings
    spiculation_no: 0
    spiculation_medium: 1
    spiculation_marked: 1
Calcification:
  type: mapping
  mappings:
    solid: 1
    Solid: 1
    Non-central: 1
    Central: 1
    Absent: 0
    absent: 0
    Fat: -1

    # self mappings
    calcification_solid: 1
    calcification_non_central: 1
    calcification_central: 1
    calcification_absent: 0
Volume:
  type: bin
  bins: [200, 400, 1000, 2000, 100000000]
