#!/bin/bash
# =================== lidc ================================
python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/lidc /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/stratified_splits/lidc/1_reader/lidc_1_reader_test.csv lidc /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache_2/lidc 15 80 80 "[5, 20, 20]" test
python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/lidc /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/stratified_splits/lidc/1_reader/lidc_1_reader_train_split_0.csv lidc /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache_2/lidc 15 80 80 "[5, 20, 20]" train_0
python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/lidc /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/stratified_splits/lidc/1_reader/lidc_1_reader_train_split_1.csv lidc /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache_2/lidc 15 80 80 "[5, 20, 20]" train_1
python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/lidc /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/stratified_splits/lidc/1_reader/lidc_1_reader_train_split_2.csv lidc /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache_2/lidc 15 80 80 "[5, 20, 20]" train_2
python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/lidc /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/stratified_splits/lidc/1_reader/lidc_1_reader_train_split_3.csv lidc /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache_2/lidc 15 80 80 "[5, 20, 20]" train_3
python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/lidc /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/stratified_splits/lidc/1_reader/lidc_1_reader_train_split_4.csv lidc /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache_2/lidc 15 80 80 "[5, 20, 20]" train_4
# ================== nlst ==================================
# python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/nlst /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/2_stage_annotations/nlst_train/rad1_stage1_1.csv nlst /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache/nlst 20 100 100 "[5, 20, 20]" train_1
# python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/nlst /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/2_stage_annotations/nlst_train/rad1_stage1_2.csv nlst /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache/nlst 20 100 100 "[5, 20, 20]" train_2
# python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/nlst /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/2_stage_annotations/nlst_train/rad1_stage1_3.csv nlst /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache/nlst 20 100 100 "[5, 20, 20]" train_3
# python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/nlst /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/2_stage_annotations/nlst_val/rad1_stage1.csv nlst /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache/nlst 20 100 100 "[5, 20, 20]" val
# python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/nlst /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/2_stage_annotations/nlst_test/rad1_stage1.csv nlst /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache/nlst 20 100 100 "[5, 20, 20]" "test"
# # ================== dsb ==================================
# python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/dsb /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/2_stage_annotations/dsb_val/rad1_stage1.csv dsb /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache/dsb 20 100 100 "[5, 20, 20]" val
# python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/dsb /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/2_stage_annotations/dsb_test/rad1_stage1.csv dsb /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache/dsb 20 100 100 "[5, 20, 20]" "test"
# # ================== internal ==============================
# python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/qct_internal_v1_500 /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/2_stage_annotations/qure_internal_v1/rad1_stage1.csv internal /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache/internal 20 100 100 "[5, 20, 20]" train_1
# python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/qure_internal_contrast_cct /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/2_stage_annotations/qure_internal_contrast/rad1_stage1.csv internal_contrast /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache/internal_contrast 20 100 100 "[5, 20, 20]" train_1
# python scripts/lung_nodule_crops.py /cache/datanas1/qct-nodules/nifti_with_annots/qiwd /home/users/souvik.mandal/projects/qct/qct_data_updates/annotations/2_stage_annotations/qiwd/rad1_stage1.csv qiwd /home/users/souvik.mandal/datasets/segm_cache/deha_net_cache/qiwd 20 100 100 "[5, 20, 20]" train_1
